"""add candidate contact information

Revision ID: 18bb4366477c
Revises: 9b13743c6553
Create Date: 2026-09-08 09:53:34.196661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bb4366477c'
down_revision: Union[str, Sequence[str], None] = '9b13743c6553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('whatsapp_number', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('candidates', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('candidates', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'portfolio_url')
    op.drop_column('candidates', 'github_url')
    op.drop_column('candidates', 'linkedin_url')
    op.drop_column('candidates', 'whatsapp_number')
    # ### end Alembic commands ###
