"""link resumes to candidates

Revision ID: 6c43b0aa615d
Revises: 7b6704e252bf
Create Date: 2026-09-04 02:51:14.338895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c43b0aa615d'
down_revision: Union[str, Sequence[str], None] = '7b6704e252bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'candidates', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'candidate_id')
    # ### end Alembic commands ###
