"""make resume file hash unique

Revision ID: 85bc69754c3a
Revises: 22477cd3a375
Create Date: 2026-09-03 13:08:52.929141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bc69754c3a'
down_revision: Union[str, Sequence[str], None] = '22477cd3a375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'resumes', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='unique')
    # ### end Alembic commands ###
