"""add job domain fields

Revision ID: 8f5383338b52
Revises: 8103eeed0fab
Create Date: 2026-09-03 10:42:42.783321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5383338b52'
down_revision: Union[str, Sequence[str], None] = '8103eeed0fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('experience_required', sa.String(length=100), nullable=False))
    op.add_column('jobs', sa.Column('employment_type', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'experience_required')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'company')
    # ### end Alembic commands ###
