"""add resume versioning fields

Revision ID: ac21d4eff97e
Revises: 96a6c2d6ca94
Create Date: 2026-09-04 03:55:11.938554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac21d4eff97e'
down_revision: Union[str, Sequence[str], None] = '96a6c2d6ca94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "resumes",
        sa.Column(
            "version",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.add_column(
        "resumes",
        sa.Column(
            "is_current",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.alter_column(
        "resumes",
        "is_current",
        server_default=None,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_current')
    op.drop_column('resumes', 'version')
    # ### end Alembic commands ###
